packages:
    - apps/*
    - packages/*

allowBuilds:
    bcrypt: true
    esbuild: true
    msgpackr-extract: true

nodeLinker: hoisted

supportedArchitectures:
    os:
        - win32
        - linux
    cpu:
        - x64
        - arm64
