packages:
  - apps/*
  - packages/*

allowBuilds:
  bcrypt: true
  esbuild: true
  msgpackr-extract: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - ','
  - b
  - c
  - d
  - e
  - esbuild
  - i
  - l
  - msgpackr-extract
  - p
  - r
  - s
  - t
  - u
  - y
